name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Valgrind
      run: sudo apt-get install -y valgrind
    - name: Compile library
      run: make
    - name: Run Tests
      run: make test
    - name: Check for memory leaks
      run: make check-leaks
